# currencyservice Deployment and Service combined YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: currencyservice
          image: kappu1512/currencyservice:latest  # Replace with your actual image path
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"  # Define the gRPC server port
            - name: DISABLE_PROFILER
              value: "true"  # Disable Google Cloud Profiler

---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: currencyservice
  ports:
    - protocol: TCP
      port: 7000        # Port on which this service will be accessible within the cluster
      targetPort: 7000  # Port on the pod where the container is listening