# paymentservice Deployment and Service combined YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: kappu1512/paymentservice:latest  # Replace with your actual image path
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"  # Define the gRPC server port
            - name: DISABLE_PROFILER
              value: "true"  # Disable Google Cloud Profiler

---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: paymentservice
  ports:
    - protocol: TCP
      port: 50051        # Port on which this service will be accessible within the cluster
      targetPort: 50051  # Port on the pod where the container is listening