# productcatalogservice Deployment and Service combined YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: productcatalogservice
          image: kappu1512/productcatalogservice:latest  # Replace with your actual image path
          ports:
            - containerPort: 3550
          env:
            - name: GOTRACEBACK
              value: "single"  # Set the GOTRACEBACK environment variable as per Docker Compose

---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: productcatalogservice
  ports:
    - protocol: TCP
      port: 3550        # Port on which this service will be accessible within the cluster
      targetPort: 3550  # Port on the pod where the container is listening