# recommendationservice Deployment and Service combined YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: recommendationservice
          image: kappu1512/recommendationservice:latest  # Replace with your actual image path
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"  # Port the service listens on
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"  # Address of productcatalogservice
            - name: DISABLE_PROFILER
              value: "true"  # Disable profiling as specified in Docker Compose

---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: recommendationservice
  ports:
    - protocol: TCP
      port: 8080        # Port on which this service will be accessible within the cluster
      targetPort: 8080  # Port on the pod where the container is listening